#coding=utf8

try:
    from . import xspcomm as xsp
except Exception as e:
    import xspcomm as xsp

if __package__ or "." in __name__:
    from .libUT_ICache import *
else:
    from libUT_ICache import *


class DUTICache(object):

    # initialize
    def __init__(self, *args, **kwargs):
        self.dut = DutUnifiedBase(*args)
        self.xclock = xsp.XClock(self.dut.simStep)
        self.xport  = xsp.XPort()
        self.xclock.Add(self.xport)
        self.event = self.xclock.getEvent()
        # set output files
        if kwargs.get("waveform_filename"):
            self.dut.SetWaveform(kwargs.get("waveform_filename"))
        if kwargs.get("coverage_filename"):
            self.dut.SetCoverage(kwargs.get("coverage_filename"))

        # all Pins
        self.clock = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.reset = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_client_out_a_ready = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_client_out_a_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.auto_client_out_a_bits_source = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.auto_client_out_a_bits_address = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.auto_client_out_d_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_opcode = xsp.XPin(xsp.XData(3, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_source = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_data = xsp.XPin(xsp.XData(256, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_corrupt = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_ftqPrefetch_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_ftqIdx_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_ftqIdx_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_bits_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_bits_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_bits_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_bits_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_softPrefetch_0_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_0_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_softPrefetch_1_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_1_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_softPrefetch_2_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_2_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_stop = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_0_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_0_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_1_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_1_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_2_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_2_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_3_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_3_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_4_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_4_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_2 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_3 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_4 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_resp_0_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_data = xsp.XPin(xsp.XData(512, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_paddr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_gpaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_exception = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_fetch_resp_0_bits_mmio = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_1_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_1_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_fetch_resp_1_bits_exception = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_toIFU = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_pmp_0_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_0_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_0_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_1_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_1_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_1_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_2_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_2_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_2_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_3_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_3_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_3_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_itlb_0_req_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_itlb_0_resp_bits_paddr_0 = xsp.XPin(xsp.XData(48, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_gpaddr_0 = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_miss = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_gpf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_pf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_af_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_itlb_1_req_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_itlb_1_resp_bits_paddr_0 = xsp.XPin(xsp.XData(48, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_gpaddr_0 = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_miss = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_gpf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_pf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_af_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_perfInfo_only_0_hit = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_only_0_miss = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit_0_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit_0_miss_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_miss_0_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_miss_0_miss_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_bank_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_error_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_error_bits_paddr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_error_bits_report_to_beu = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_csr_pf_enable = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_csr_parity_enable = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fencei = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_flush = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)


        # BindDPI
        self.clock.BindDPIPtr(self.dut.GetDPIHandle("clock", 0), self.dut.GetDPIHandle("clock", 1))
        self.reset.BindDPIPtr(self.dut.GetDPIHandle("reset", 0), self.dut.GetDPIHandle("reset", 1))
        self.auto_client_out_a_ready.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_ready", 0), self.dut.GetDPIHandle("auto_client_out_a_ready", 1))
        self.auto_client_out_a_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_valid", 0), self.dut.GetDPIHandle("auto_client_out_a_valid", 1))
        self.auto_client_out_a_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_bits_source", 0), self.dut.GetDPIHandle("auto_client_out_a_bits_source", 1))
        self.auto_client_out_a_bits_address.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_bits_address", 0), self.dut.GetDPIHandle("auto_client_out_a_bits_address", 1))
        self.auto_client_out_d_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_valid", 0), self.dut.GetDPIHandle("auto_client_out_d_valid", 1))
        self.auto_client_out_d_bits_opcode.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_opcode", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_opcode", 1))
        self.auto_client_out_d_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_source", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_source", 1))
        self.auto_client_out_d_bits_data.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_data", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_data", 1))
        self.auto_client_out_d_bits_corrupt.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_corrupt", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_corrupt", 1))
        self.io_ftqPrefetch_req_ready.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_ready", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_ready", 1))
        self.io_ftqPrefetch_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_valid", 1))
        self.io_ftqPrefetch_req_bits_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_startAddr", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_startAddr", 1))
        self.io_ftqPrefetch_req_bits_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_nextlineStart", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_nextlineStart", 1))
        self.io_ftqPrefetch_req_bits_ftqIdx_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_flag", 1))
        self.io_ftqPrefetch_req_bits_ftqIdx_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_value", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_valid", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_bits_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_flag", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_bits_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_value", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_valid", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_bits_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_flag", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_bits_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_value", 1))
        self.io_softPrefetch_0_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_0_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_0_valid", 1))
        self.io_softPrefetch_0_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_0_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_0_bits_vaddr", 1))
        self.io_softPrefetch_1_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_1_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_1_valid", 1))
        self.io_softPrefetch_1_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_1_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_1_bits_vaddr", 1))
        self.io_softPrefetch_2_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_2_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_2_valid", 1))
        self.io_softPrefetch_2_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_2_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_2_bits_vaddr", 1))
        self.io_stop.BindDPIPtr(self.dut.GetDPIHandle("io_stop", 0), self.dut.GetDPIHandle("io_stop", 1))
        self.io_fetch_req_ready.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_ready", 0), self.dut.GetDPIHandle("io_fetch_req_ready", 1))
        self.io_fetch_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_valid", 0), self.dut.GetDPIHandle("io_fetch_req_valid", 1))
        self.io_fetch_req_bits_pcMemRead_0_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_0_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_1_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_1_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_2_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_2_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_3_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_3_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_4_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_4_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_nextlineStart", 1))
        self.io_fetch_req_bits_readValid_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_0", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_0", 1))
        self.io_fetch_req_bits_readValid_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_1", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_1", 1))
        self.io_fetch_req_bits_readValid_2.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_2", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_2", 1))
        self.io_fetch_req_bits_readValid_3.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_3", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_3", 1))
        self.io_fetch_req_bits_readValid_4.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_4", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_4", 1))
        self.io_fetch_resp_0_valid.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_valid", 0), self.dut.GetDPIHandle("io_fetch_resp_0_valid", 1))
        self.io_fetch_resp_0_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_vaddr", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_vaddr", 1))
        self.io_fetch_resp_0_bits_data.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_data", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_data", 1))
        self.io_fetch_resp_0_bits_paddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_paddr", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_paddr", 1))
        self.io_fetch_resp_0_bits_gpaddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_gpaddr", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_gpaddr", 1))
        self.io_fetch_resp_0_bits_exception.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_exception", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_exception", 1))
        self.io_fetch_resp_0_bits_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_0_bits_mmio", 0), self.dut.GetDPIHandle("io_fetch_resp_0_bits_mmio", 1))
        self.io_fetch_resp_1_valid.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_1_valid", 0), self.dut.GetDPIHandle("io_fetch_resp_1_valid", 1))
        self.io_fetch_resp_1_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_1_bits_vaddr", 0), self.dut.GetDPIHandle("io_fetch_resp_1_bits_vaddr", 1))
        self.io_fetch_resp_1_bits_exception.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_1_bits_exception", 0), self.dut.GetDPIHandle("io_fetch_resp_1_bits_exception", 1))
        self.io_toIFU.BindDPIPtr(self.dut.GetDPIHandle("io_toIFU", 0), self.dut.GetDPIHandle("io_toIFU", 1))
        self.io_pmp_0_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_0_req_bits_addr", 1))
        self.io_pmp_0_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_0_resp_instr", 1))
        self.io_pmp_0_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_0_resp_mmio", 1))
        self.io_pmp_1_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_1_req_bits_addr", 1))
        self.io_pmp_1_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_1_resp_instr", 1))
        self.io_pmp_1_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_1_resp_mmio", 1))
        self.io_pmp_2_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_2_req_bits_addr", 1))
        self.io_pmp_2_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_2_resp_instr", 1))
        self.io_pmp_2_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_2_resp_mmio", 1))
        self.io_pmp_3_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_3_req_bits_addr", 1))
        self.io_pmp_3_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_3_resp_instr", 1))
        self.io_pmp_3_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_3_resp_mmio", 1))
        self.io_itlb_0_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_req_valid", 0), self.dut.GetDPIHandle("io_itlb_0_req_valid", 1))
        self.io_itlb_0_req_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_req_bits_vaddr", 0), self.dut.GetDPIHandle("io_itlb_0_req_bits_vaddr", 1))
        self.io_itlb_0_resp_bits_paddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_paddr_0", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_paddr_0", 1))
        self.io_itlb_0_resp_bits_gpaddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_gpaddr_0", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_gpaddr_0", 1))
        self.io_itlb_0_resp_bits_miss.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_miss", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_miss", 1))
        self.io_itlb_0_resp_bits_excp_0_gpf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_gpf_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_gpf_instr", 1))
        self.io_itlb_0_resp_bits_excp_0_pf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_pf_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_pf_instr", 1))
        self.io_itlb_0_resp_bits_excp_0_af_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_af_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_af_instr", 1))
        self.io_itlb_1_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_req_valid", 0), self.dut.GetDPIHandle("io_itlb_1_req_valid", 1))
        self.io_itlb_1_req_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_req_bits_vaddr", 0), self.dut.GetDPIHandle("io_itlb_1_req_bits_vaddr", 1))
        self.io_itlb_1_resp_bits_paddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_paddr_0", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_paddr_0", 1))
        self.io_itlb_1_resp_bits_gpaddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_gpaddr_0", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_gpaddr_0", 1))
        self.io_itlb_1_resp_bits_miss.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_miss", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_miss", 1))
        self.io_itlb_1_resp_bits_excp_0_gpf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_gpf_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_gpf_instr", 1))
        self.io_itlb_1_resp_bits_excp_0_pf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_pf_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_pf_instr", 1))
        self.io_itlb_1_resp_bits_excp_0_af_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_af_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_af_instr", 1))
        self.io_perfInfo_only_0_hit.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_only_0_hit", 0), self.dut.GetDPIHandle("io_perfInfo_only_0_hit", 1))
        self.io_perfInfo_only_0_miss.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_only_0_miss", 0), self.dut.GetDPIHandle("io_perfInfo_only_0_miss", 1))
        self.io_perfInfo_hit_0_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit_0_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_hit_0_hit_1", 1))
        self.io_perfInfo_hit_0_miss_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit_0_miss_1", 0), self.dut.GetDPIHandle("io_perfInfo_hit_0_miss_1", 1))
        self.io_perfInfo_miss_0_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_miss_0_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_miss_0_hit_1", 1))
        self.io_perfInfo_miss_0_miss_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_miss_0_miss_1", 0), self.dut.GetDPIHandle("io_perfInfo_miss_0_miss_1", 1))
        self.io_perfInfo_bank_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_bank_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_bank_hit_1", 1))
        self.io_perfInfo_hit.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit", 0), self.dut.GetDPIHandle("io_perfInfo_hit", 1))
        self.io_error_valid.BindDPIPtr(self.dut.GetDPIHandle("io_error_valid", 0), self.dut.GetDPIHandle("io_error_valid", 1))
        self.io_error_bits_paddr.BindDPIPtr(self.dut.GetDPIHandle("io_error_bits_paddr", 0), self.dut.GetDPIHandle("io_error_bits_paddr", 1))
        self.io_error_bits_report_to_beu.BindDPIPtr(self.dut.GetDPIHandle("io_error_bits_report_to_beu", 0), self.dut.GetDPIHandle("io_error_bits_report_to_beu", 1))
        self.io_csr_pf_enable.BindDPIPtr(self.dut.GetDPIHandle("io_csr_pf_enable", 0), self.dut.GetDPIHandle("io_csr_pf_enable", 1))
        self.io_csr_parity_enable.BindDPIPtr(self.dut.GetDPIHandle("io_csr_parity_enable", 0), self.dut.GetDPIHandle("io_csr_parity_enable", 1))
        self.io_fencei.BindDPIPtr(self.dut.GetDPIHandle("io_fencei", 0), self.dut.GetDPIHandle("io_fencei", 1))
        self.io_flush.BindDPIPtr(self.dut.GetDPIHandle("io_flush", 0), self.dut.GetDPIHandle("io_flush", 1))


        # Add2Port
        self.xport.Add("clock", self.clock.xdata)
        self.xport.Add("reset", self.reset.xdata)
        self.xport.Add("auto_client_out_a_ready", self.auto_client_out_a_ready.xdata)
        self.xport.Add("auto_client_out_a_valid", self.auto_client_out_a_valid.xdata)
        self.xport.Add("auto_client_out_a_bits_source", self.auto_client_out_a_bits_source.xdata)
        self.xport.Add("auto_client_out_a_bits_address", self.auto_client_out_a_bits_address.xdata)
        self.xport.Add("auto_client_out_d_valid", self.auto_client_out_d_valid.xdata)
        self.xport.Add("auto_client_out_d_bits_opcode", self.auto_client_out_d_bits_opcode.xdata)
        self.xport.Add("auto_client_out_d_bits_source", self.auto_client_out_d_bits_source.xdata)
        self.xport.Add("auto_client_out_d_bits_data", self.auto_client_out_d_bits_data.xdata)
        self.xport.Add("auto_client_out_d_bits_corrupt", self.auto_client_out_d_bits_corrupt.xdata)
        self.xport.Add("io_ftqPrefetch_req_ready", self.io_ftqPrefetch_req_ready.xdata)
        self.xport.Add("io_ftqPrefetch_req_valid", self.io_ftqPrefetch_req_valid.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_startAddr", self.io_ftqPrefetch_req_bits_startAddr.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_nextlineStart", self.io_ftqPrefetch_req_bits_nextlineStart.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_ftqIdx_flag", self.io_ftqPrefetch_req_bits_ftqIdx_flag.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_ftqIdx_value", self.io_ftqPrefetch_req_bits_ftqIdx_value.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_valid", self.io_ftqPrefetch_flushFromBpu_s2_valid.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_bits_flag", self.io_ftqPrefetch_flushFromBpu_s2_bits_flag.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_bits_value", self.io_ftqPrefetch_flushFromBpu_s2_bits_value.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_valid", self.io_ftqPrefetch_flushFromBpu_s3_valid.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_bits_flag", self.io_ftqPrefetch_flushFromBpu_s3_bits_flag.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_bits_value", self.io_ftqPrefetch_flushFromBpu_s3_bits_value.xdata)
        self.xport.Add("io_softPrefetch_0_valid", self.io_softPrefetch_0_valid.xdata)
        self.xport.Add("io_softPrefetch_0_bits_vaddr", self.io_softPrefetch_0_bits_vaddr.xdata)
        self.xport.Add("io_softPrefetch_1_valid", self.io_softPrefetch_1_valid.xdata)
        self.xport.Add("io_softPrefetch_1_bits_vaddr", self.io_softPrefetch_1_bits_vaddr.xdata)
        self.xport.Add("io_softPrefetch_2_valid", self.io_softPrefetch_2_valid.xdata)
        self.xport.Add("io_softPrefetch_2_bits_vaddr", self.io_softPrefetch_2_bits_vaddr.xdata)
        self.xport.Add("io_stop", self.io_stop.xdata)
        self.xport.Add("io_fetch_req_ready", self.io_fetch_req_ready.xdata)
        self.xport.Add("io_fetch_req_valid", self.io_fetch_req_valid.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_0_startAddr", self.io_fetch_req_bits_pcMemRead_0_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_0_nextlineStart", self.io_fetch_req_bits_pcMemRead_0_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_1_startAddr", self.io_fetch_req_bits_pcMemRead_1_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_1_nextlineStart", self.io_fetch_req_bits_pcMemRead_1_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_2_startAddr", self.io_fetch_req_bits_pcMemRead_2_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_2_nextlineStart", self.io_fetch_req_bits_pcMemRead_2_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_3_startAddr", self.io_fetch_req_bits_pcMemRead_3_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_3_nextlineStart", self.io_fetch_req_bits_pcMemRead_3_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_4_startAddr", self.io_fetch_req_bits_pcMemRead_4_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_4_nextlineStart", self.io_fetch_req_bits_pcMemRead_4_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_0", self.io_fetch_req_bits_readValid_0.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_1", self.io_fetch_req_bits_readValid_1.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_2", self.io_fetch_req_bits_readValid_2.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_3", self.io_fetch_req_bits_readValid_3.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_4", self.io_fetch_req_bits_readValid_4.xdata)
        self.xport.Add("io_fetch_resp_0_valid", self.io_fetch_resp_0_valid.xdata)
        self.xport.Add("io_fetch_resp_0_bits_vaddr", self.io_fetch_resp_0_bits_vaddr.xdata)
        self.xport.Add("io_fetch_resp_0_bits_data", self.io_fetch_resp_0_bits_data.xdata)
        self.xport.Add("io_fetch_resp_0_bits_paddr", self.io_fetch_resp_0_bits_paddr.xdata)
        self.xport.Add("io_fetch_resp_0_bits_gpaddr", self.io_fetch_resp_0_bits_gpaddr.xdata)
        self.xport.Add("io_fetch_resp_0_bits_exception", self.io_fetch_resp_0_bits_exception.xdata)
        self.xport.Add("io_fetch_resp_0_bits_mmio", self.io_fetch_resp_0_bits_mmio.xdata)
        self.xport.Add("io_fetch_resp_1_valid", self.io_fetch_resp_1_valid.xdata)
        self.xport.Add("io_fetch_resp_1_bits_vaddr", self.io_fetch_resp_1_bits_vaddr.xdata)
        self.xport.Add("io_fetch_resp_1_bits_exception", self.io_fetch_resp_1_bits_exception.xdata)
        self.xport.Add("io_toIFU", self.io_toIFU.xdata)
        self.xport.Add("io_pmp_0_req_bits_addr", self.io_pmp_0_req_bits_addr.xdata)
        self.xport.Add("io_pmp_0_resp_instr", self.io_pmp_0_resp_instr.xdata)
        self.xport.Add("io_pmp_0_resp_mmio", self.io_pmp_0_resp_mmio.xdata)
        self.xport.Add("io_pmp_1_req_bits_addr", self.io_pmp_1_req_bits_addr.xdata)
        self.xport.Add("io_pmp_1_resp_instr", self.io_pmp_1_resp_instr.xdata)
        self.xport.Add("io_pmp_1_resp_mmio", self.io_pmp_1_resp_mmio.xdata)
        self.xport.Add("io_pmp_2_req_bits_addr", self.io_pmp_2_req_bits_addr.xdata)
        self.xport.Add("io_pmp_2_resp_instr", self.io_pmp_2_resp_instr.xdata)
        self.xport.Add("io_pmp_2_resp_mmio", self.io_pmp_2_resp_mmio.xdata)
        self.xport.Add("io_pmp_3_req_bits_addr", self.io_pmp_3_req_bits_addr.xdata)
        self.xport.Add("io_pmp_3_resp_instr", self.io_pmp_3_resp_instr.xdata)
        self.xport.Add("io_pmp_3_resp_mmio", self.io_pmp_3_resp_mmio.xdata)
        self.xport.Add("io_itlb_0_req_valid", self.io_itlb_0_req_valid.xdata)
        self.xport.Add("io_itlb_0_req_bits_vaddr", self.io_itlb_0_req_bits_vaddr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_paddr_0", self.io_itlb_0_resp_bits_paddr_0.xdata)
        self.xport.Add("io_itlb_0_resp_bits_gpaddr_0", self.io_itlb_0_resp_bits_gpaddr_0.xdata)
        self.xport.Add("io_itlb_0_resp_bits_miss", self.io_itlb_0_resp_bits_miss.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_gpf_instr", self.io_itlb_0_resp_bits_excp_0_gpf_instr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_pf_instr", self.io_itlb_0_resp_bits_excp_0_pf_instr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_af_instr", self.io_itlb_0_resp_bits_excp_0_af_instr.xdata)
        self.xport.Add("io_itlb_1_req_valid", self.io_itlb_1_req_valid.xdata)
        self.xport.Add("io_itlb_1_req_bits_vaddr", self.io_itlb_1_req_bits_vaddr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_paddr_0", self.io_itlb_1_resp_bits_paddr_0.xdata)
        self.xport.Add("io_itlb_1_resp_bits_gpaddr_0", self.io_itlb_1_resp_bits_gpaddr_0.xdata)
        self.xport.Add("io_itlb_1_resp_bits_miss", self.io_itlb_1_resp_bits_miss.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_gpf_instr", self.io_itlb_1_resp_bits_excp_0_gpf_instr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_pf_instr", self.io_itlb_1_resp_bits_excp_0_pf_instr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_af_instr", self.io_itlb_1_resp_bits_excp_0_af_instr.xdata)
        self.xport.Add("io_perfInfo_only_0_hit", self.io_perfInfo_only_0_hit.xdata)
        self.xport.Add("io_perfInfo_only_0_miss", self.io_perfInfo_only_0_miss.xdata)
        self.xport.Add("io_perfInfo_hit_0_hit_1", self.io_perfInfo_hit_0_hit_1.xdata)
        self.xport.Add("io_perfInfo_hit_0_miss_1", self.io_perfInfo_hit_0_miss_1.xdata)
        self.xport.Add("io_perfInfo_miss_0_hit_1", self.io_perfInfo_miss_0_hit_1.xdata)
        self.xport.Add("io_perfInfo_miss_0_miss_1", self.io_perfInfo_miss_0_miss_1.xdata)
        self.xport.Add("io_perfInfo_bank_hit_1", self.io_perfInfo_bank_hit_1.xdata)
        self.xport.Add("io_perfInfo_hit", self.io_perfInfo_hit.xdata)
        self.xport.Add("io_error_valid", self.io_error_valid.xdata)
        self.xport.Add("io_error_bits_paddr", self.io_error_bits_paddr.xdata)
        self.xport.Add("io_error_bits_report_to_beu", self.io_error_bits_report_to_beu.xdata)
        self.xport.Add("io_csr_pf_enable", self.io_csr_pf_enable.xdata)
        self.xport.Add("io_csr_parity_enable", self.io_csr_parity_enable.xdata)
        self.xport.Add("io_fencei", self.io_fencei.xdata)
        self.xport.Add("io_flush", self.io_flush.xdata)


        # Cascaded ports
        self.auto_client_out = self.xport.NewSubPort("auto_client_out_")
        self.auto_client_out_a = self.xport.NewSubPort("auto_client_out_a_")
        self.auto_client_out_a_bits = self.xport.NewSubPort("auto_client_out_a_bits_")
        self.auto_client_out_d = self.xport.NewSubPort("auto_client_out_d_")
        self.auto_client_out_d_bits = self.xport.NewSubPort("auto_client_out_d_bits_")
        self.io = self.xport.NewSubPort("io_")
        self.io_csr = self.xport.NewSubPort("io_csr_")
        self.io_error = self.xport.NewSubPort("io_error_")
        self.io_error_bits = self.xport.NewSubPort("io_error_bits_")
        self.io_fetch = self.xport.NewSubPort("io_fetch_")
        self.io_fetch_req = self.xport.NewSubPort("io_fetch_req_")
        self.io_fetch_req_bits = self.xport.NewSubPort("io_fetch_req_bits_")
        self.io_fetch_req_bits_pcMemRead = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_")
        self.io_fetch_req_bits_pcMemRead_0 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_0_")
        self.io_fetch_req_bits_pcMemRead_1 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_1_")
        self.io_fetch_req_bits_pcMemRead_2 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_2_")
        self.io_fetch_req_bits_pcMemRead_3 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_3_")
        self.io_fetch_req_bits_pcMemRead_4 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_4_")
        self.io_fetch_req_bits_readValid = self.xport.NewSubPort("io_fetch_req_bits_readValid_")
        self.io_fetch_resp = self.xport.NewSubPort("io_fetch_resp_")
        self.io_fetch_resp_0 = self.xport.NewSubPort("io_fetch_resp_0_")
        self.io_fetch_resp_0_bits = self.xport.NewSubPort("io_fetch_resp_0_bits_")
        self.io_fetch_resp_1 = self.xport.NewSubPort("io_fetch_resp_1_")
        self.io_fetch_resp_1_bits = self.xport.NewSubPort("io_fetch_resp_1_bits_")
        self.io_ftqPrefetch = self.xport.NewSubPort("io_ftqPrefetch_")
        self.io_ftqPrefetch_flushFromBpu = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_")
        self.io_ftqPrefetch_flushFromBpu_s2 = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s2_")
        self.io_ftqPrefetch_flushFromBpu_s2_bits = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s2_bits_")
        self.io_ftqPrefetch_flushFromBpu_s3 = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s3_")
        self.io_ftqPrefetch_flushFromBpu_s3_bits = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s3_bits_")
        self.io_ftqPrefetch_req = self.xport.NewSubPort("io_ftqPrefetch_req_")
        self.io_ftqPrefetch_req_bits = self.xport.NewSubPort("io_ftqPrefetch_req_bits_")
        self.io_ftqPrefetch_req_bits_ftqIdx = self.xport.NewSubPort("io_ftqPrefetch_req_bits_ftqIdx_")
        self.io_itlb = self.xport.NewSubPort("io_itlb_")
        self.io_itlb_0 = self.xport.NewSubPort("io_itlb_0_")
        self.io_itlb_0_req = self.xport.NewSubPort("io_itlb_0_req_")
        self.io_itlb_0_resp_bits = self.xport.NewSubPort("io_itlb_0_resp_bits_")
        self.io_itlb_0_resp_bits_excp = self.xport.NewSubPort("io_itlb_0_resp_bits_excp_")
        self.io_itlb_0_resp_bits_excp_0 = self.xport.NewSubPort("io_itlb_0_resp_bits_excp_0_")
        self.io_itlb_0_resp_bits_gpaddr = self.xport.NewSubPort("io_itlb_0_resp_bits_gpaddr_")
        self.io_itlb_0_resp_bits_paddr = self.xport.NewSubPort("io_itlb_0_resp_bits_paddr_")
        self.io_itlb_1 = self.xport.NewSubPort("io_itlb_1_")
        self.io_itlb_1_req = self.xport.NewSubPort("io_itlb_1_req_")
        self.io_itlb_1_resp_bits = self.xport.NewSubPort("io_itlb_1_resp_bits_")
        self.io_itlb_1_resp_bits_excp = self.xport.NewSubPort("io_itlb_1_resp_bits_excp_")
        self.io_itlb_1_resp_bits_excp_0 = self.xport.NewSubPort("io_itlb_1_resp_bits_excp_0_")
        self.io_itlb_1_resp_bits_gpaddr = self.xport.NewSubPort("io_itlb_1_resp_bits_gpaddr_")
        self.io_itlb_1_resp_bits_paddr = self.xport.NewSubPort("io_itlb_1_resp_bits_paddr_")
        self.io_perfInfo = self.xport.NewSubPort("io_perfInfo_")
        self.io_perfInfo_bank_hit = self.xport.NewSubPort("io_perfInfo_bank_hit_")
        self.io_perfInfo_miss = self.xport.NewSubPort("io_perfInfo_miss_")
        self.io_perfInfo_miss_0 = self.xport.NewSubPort("io_perfInfo_miss_0_")
        self.io_perfInfo_miss_0_hit = self.xport.NewSubPort("io_perfInfo_miss_0_hit_")
        self.io_perfInfo_miss_0_miss = self.xport.NewSubPort("io_perfInfo_miss_0_miss_")
        self.io_perfInfo_only = self.xport.NewSubPort("io_perfInfo_only_")
        self.io_perfInfo_only_0 = self.xport.NewSubPort("io_perfInfo_only_0_")
        self.io_pmp = self.xport.NewSubPort("io_pmp_")
        self.io_pmp_0 = self.xport.NewSubPort("io_pmp_0_")
        self.io_pmp_0_resp = self.xport.NewSubPort("io_pmp_0_resp_")
        self.io_pmp_1 = self.xport.NewSubPort("io_pmp_1_")
        self.io_pmp_1_resp = self.xport.NewSubPort("io_pmp_1_resp_")
        self.io_pmp_2 = self.xport.NewSubPort("io_pmp_2_")
        self.io_pmp_2_resp = self.xport.NewSubPort("io_pmp_2_resp_")
        self.io_pmp_3 = self.xport.NewSubPort("io_pmp_3_")
        self.io_pmp_3_resp = self.xport.NewSubPort("io_pmp_3_resp_")
        self.io_softPrefetch = self.xport.NewSubPort("io_softPrefetch_")
        self.io_softPrefetch_0 = self.xport.NewSubPort("io_softPrefetch_0_")
        self.io_softPrefetch_1 = self.xport.NewSubPort("io_softPrefetch_1_")
        self.io_softPrefetch_2 = self.xport.NewSubPort("io_softPrefetch_2_")


    def __del__(self):
        self.Finish()

    ################################
    #         User APIs            #
    ################################
    def InitClock(self, name: str):
        self.xclock.Add(self.xport[name])

    def Step(self, i:int = 1):
        self.xclock.Step(i)

    def StepRis(self, callback, args=(), kwargs={}):
        self.xclock.StepRis(callback, args, kwargs)

    def StepFal(self, callback, args=(), kwargs={}):
        self.xclock.StepFal(callback, args, kwargs)

    def SetWaveform(self, filename: str):
        self.dut.SetWaveform(filename)

    def SetCoverage(self, filename: str):
        self.dut.SetCoverage(filename)

    def Finish(self):
        self.dut.Finish()

    def RefreshComb(self):
        self.dut.RefreshComb()

    ################################
    #      End of User APIs        #
    ################################

    def __getitem__(self, key):
        return xsp.XPin(self.port[key], self.event)

    # Async APIs wrapped from XClock
    async def AStep(self,i: int):
        return await self.xclock.AStep(i)

    async def Acondition(self,fc_cheker):
        return await self.xclock.ACondition(fc_cheker)

    def RunStep(self,i: int):
        return self.xclock.RunStep(i)

if __name__=="__main__":
    dut=DUTICache()
    dut.Step(100)
